### ISSUE TITLE
API only

### ISSUE THREAD

**Issue by silentlight** [celo-org/rosetta#101]
Hi guys,

Is it possible to run your rosetta implementation just the API portion? I would like to point to a url of my node and have it working without a need for local geth.

**Comment by silentlight** [comment]
Anyone??

**Comment by eelanagaraj** [comment]
Hey @silentlight I don't think it's currently possible and according to the [Rosetta docs](https://www.rosetta-api.org/docs/1.4.6/common_mistakes.html) (first one, under "Connecting to a Block Explorer or External Node"), the Rosetta implementation needs to connect to a local node.
