### ISSUE TITLE
Rosetta - Users SBAT construct transactions and pay for gas with other currencies

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/rosetta#137]
Currently, users constructing transactions via `/construction/*` (on branch `/beta/construction` for `rosetta` and on `main` for `rosetta-cusd`) can only pay for gas in CELO. `rosetta` will need to be modified to allow additional currencies to be specified via the `construction` endpoints.

This will also require modifying the `celo.ros` file to pay for gas with multiple currencies. (This may or may not be possible).

It's possible that this requires little modification and therefore is done far quicker than the estimate, but it's also possible that investigating how to do this reveals that it requires a deeper refactor than is at first apparent, which would mean the estimate should be higher. Estimate range: low end 3 days; higher end 8. This may need to be rescoped/re-estimated once it is clearer how long this will take (which we will only figure out once we actually look into how to implement this at a deeper level).

Potentially split this into a second issue for `rosetta-cusd`.

**Comment by aslawson** [comment]
closed related
https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/rosetta/140
