### ISSUE TITLE
Investigate (+ clean up) the external `celo-monorepo` and `celo-blockchain` deps in Rosetta

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/rosetta#154]
When building from source, the previous instructions required having a local version of the `celo-monorepo` and `celo-blockchain`. Investigate if these are necessary any more. They are both required for the `make-gen-contracts` command that generates contract bindings, but from early investigation, I think that isn't actually being used by Rosetta (in favor of kliento).

Motivation:
- Getting rid of additional stuff in order to build from source would make it easier for folks to get set up (not need to build the monorepo + blockchain)
- If it turns out we need them, we need to update this information + have a plan for dealing with contracts releases (i.e. making sure that the generated contracts versions correspond exactly to the versions of contracts on the different networks) and adding docs to the README for this

Estimate: probably around a day (perhaps a bit of additional time cleaning up + testing). This excludes time for dealing with contracts releases if it turns out we need the monorepo/blockchain dependencies to build from source.

TODOs:
- [x] `celo-monorepo` dep investigation
- [x] `celo-blockchain` dep investigation
- [x] update readme as necessary

**Comment by aslawson** [comment]
@eelanagaraj is this more a headache for existing users or just a barrier for greater adoption of rosetta?

**Comment by eelanagaraj** [comment]
@aslawson both, but motivation here would be the former particularly in the context of testing out the new construction changes. Happy to provide more context on this as well, but generally: I think this has caused frustration for getting this set up on new environments, and this is something that has come up multiple times and feels like a "detoil" -- not urgent but will probably save us time down the line if we don't need folks to build the monorepo in particular.
