### ISSUE TITLE
Investigate other Value=0 cases for events in `TxOpsFromLogs`

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/rosetta#161]
There have been two edge cases identified thus far (`GoldLocked` and `GoldWithdrawn`). Take time to investigate whether it's possible to skip transfer creation for all `Value=0` transactions in this function, or if there is a more robust solution here to prevent future issues with this.

Need to add for GoldWithdrawn, GoldLocked, GoldRelocked, GoldUnlocked ( + Election events as well)

Solution may be as simple as adding a check (Value==0, exclude those transfers), but double check that this does not break anything for the other events. (+ run full CLI checks if possible).

**Comment by aslawson** [comment]
Seems like remaining work here from DevX is to add this to checks to all the methods:GoldWithdrawn, GoldLocked, GoldRelocked, GoldUnlocked

Contract Changes are here: https://github.com/celo-org/celo-monorepo/issues/7758

**Comment by barbaraliau** [comment]
Related to #7758

**Comment by AlexBHarley** [comment]
Some findings here. Logs are only matched with transfer if they are one of

- `lockGold`
- `unlockGold`
- `slash`.

This logic can be seen [here](https://github.com/celo-org/rosetta/blob/5e63a3ca37099211eab86e9fc0e734af34a6b0f4/analyzer/operations.go#L411).
