### ISSUE TITLE
Remove rust as a build step

### ISSUE THREAD

**Issue by mcortesi** [celo-org/rosetta#58]
Can be done after https://github.com/celo-org/celo-blockchain/pull/987

**Comment by gakonst** [comment]
@mcortesi We have exposed a new go library under https://github.com/celo-org/celo-bls-go/, this removes the need for a rust toolchain altogether.

**Comment by kobigurk** [comment]
Yep! If you use celo-bls-go, rust is not longer needed. See celo-blockchain master for how it's done.
